# Configuration File for the Python Git Server Thing

# Sets the directory for backup repos from github and repositories from the 'micro server'
backup-dir: './backups'

# Task Scheduler for the regular 'git pull' command.
task-scheduler: 'cron'
api-server: github

# Enables auto refreshing of the page.
auto-refresh: True

# Frequency for the auto refreshing of the page.
refresh-frequency: 300

# Sets options for when the flask app is running
app-port: 8080
app-debug: True
app-host: 127.0.0.1
